[tool.pytest.ini_options]
testpaths=["tests"]

[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "setuptools_scm>=6.2",
]

[tool.setuptools_scm]
write_to = "ovs_dbg/_version.py"

[tool.black]
line-length = 79
exclude="ovs"
