name: Publish to TestPyPI

on:
  push:
    branches:
      - main
      - master

jobs:
  build-n-publish:
    name: Build and Publish to PyPI or TestPyPI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install pypa/build
        run: |
          python -m pip install build --user
      - name: Install vendored ovs
        run: ./prepare.sh
      - name: Build binary wheel and source tarball
        run: |
          python -m build --sdist --wheel .
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
